#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x3602B07F55D0C732 (gray@gnu.org)
#
Name     : compat-gdbm-soname4
Version  : 1.14
Release  : 2
URL      : https://mirrors.kernel.org/gnu/gdbm/gdbm-1.14.tar.gz
Source0  : https://mirrors.kernel.org/gnu/gdbm/gdbm-1.14.tar.gz
Source1 : https://mirrors.kernel.org/gnu/gdbm/gdbm-1.14.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
Requires: compat-gdbm-soname4-lib = %{version}-%{release}
Requires: compat-gdbm-soname4-license = %{version}-%{release}
Requires: compat-gdbm-soname4-locales = %{version}-%{release}
BuildRequires : bison
BuildRequires : dejagnu
BuildRequires : expect
BuildRequires : flex
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : ncurses-dev
BuildRequires : readline-dev
BuildRequires : tcl

%description
See the end of file for copying conditions.
* Introduction
This file contains brief information about configuring, testing
and using GNU dbm.  It is *not* intended as a replacement
for the documentation, instead it is provided as a brief reference
only. The complete documentation is available in doc/ subdirectory.
To read the manpage without installing the package use `man
doc/gdbm.3'.  To read texinfo documentation without installing the
package, run `info -f doc/gdbm.info'.  After the package is installed
the documentation can be accessed by running `man gdbm' and
`info gdbm'.

%package lib
Summary: lib components for the compat-gdbm-soname4 package.
Group: Libraries
Requires: compat-gdbm-soname4-license = %{version}-%{release}

%description lib
lib components for the compat-gdbm-soname4 package.


%package lib32
Summary: lib32 components for the compat-gdbm-soname4 package.
Group: Default
Requires: compat-gdbm-soname4-license = %{version}-%{release}

%description lib32
lib32 components for the compat-gdbm-soname4 package.


%package license
Summary: license components for the compat-gdbm-soname4 package.
Group: Default

%description license
license components for the compat-gdbm-soname4 package.


%package locales
Summary: locales components for the compat-gdbm-soname4 package.
Group: Default

%description locales
locales components for the compat-gdbm-soname4 package.


%prep
%setup -q -n gdbm-1.14
pushd ..
cp -a gdbm-1.14 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1571265644
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static --enable-libgdbm-compat
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static --enable-libgdbm-compat   --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check
cd ../build32;
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1571265644
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-gdbm-soname4
cp %{_builddir}/gdbm-1.14/COPYING %{buildroot}/usr/share/package-licenses/compat-gdbm-soname4/70e64fe9090c157e441681779e0f31aad34f35cb
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install
%find_lang gdbm
## Remove excluded files
rm -f %{buildroot}/usr/bin/gdbm_dump
rm -f %{buildroot}/usr/bin/gdbm_load
rm -f %{buildroot}/usr/bin/gdbmtool
rm -f %{buildroot}/usr/include/dbm.h
rm -f %{buildroot}/usr/include/gdbm.h
rm -f %{buildroot}/usr/include/ndbm.h
rm -f %{buildroot}/usr/lib32/libgdbm.so
rm -f %{buildroot}/usr/lib32/libgdbm_compat.so
rm -f %{buildroot}/usr/lib64/libgdbm.so
rm -f %{buildroot}/usr/lib64/libgdbm_compat.so
rm -f %{buildroot}/usr/share/info/gdbm.info
rm -f %{buildroot}/usr/share/man/man1/gdbm_dump.1
rm -f %{buildroot}/usr/share/man/man1/gdbm_load.1
rm -f %{buildroot}/usr/share/man/man1/gdbmtool.1
rm -f %{buildroot}/usr/share/man/man3/gdbm.3

%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgdbm.so.4
/usr/lib64/libgdbm.so.4.0.0
/usr/lib64/libgdbm_compat.so.4
/usr/lib64/libgdbm_compat.so.4.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libgdbm.so.4
/usr/lib32/libgdbm.so.4.0.0
/usr/lib32/libgdbm_compat.so.4
/usr/lib32/libgdbm_compat.so.4.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-gdbm-soname4/70e64fe9090c157e441681779e0f31aad34f35cb

%files locales -f gdbm.lang
%defattr(-,root,root,-)

